### ISSUE TITLE
Add option to set attributes of XML Elements

### ISSUE THREAD

**Issue by StefanHagen** [markkorput/xsd-populator#5]
Hi markkorput! Thanks for creating these nice gems for populating an XML based on an XSD. It's coming in very handy on a project I'm working on now. 

One thing, on some (ComplexType) XML elements I need to set attributes as well as a value. Is there a way to do this or is this something that could be added in the future?

Regards, Stefan

**Comment by markkorput** [comment]
Hey @StefanHagen, I haven't touched this gem for a while, but I'm happy to hear it's helping someone.

As for your question, yes that's possible. There are multiple ways to do this. I guess the documentation is a bit lacking and I'm afraid I'm not gonna be able to put time into that anytime soon, but I suggest you have a look at the specs, they can give you some idea about how to do things.

I just pushed [a commit which includes two new tests](https://github.com/markkorput/xsd-populator/commit/eb0c262388e2f188d6ef8096419a1f3a2bfe4911) which demonstrate how to specify the value of attributes (either using a value-provider for the attribute's path, or using an informer-provider for the attribute's element).
